// Code generated by MockGen. DO NOT EDIT.
// Source: wallet service client interface

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockWalletServiceClient is a mock of WalletServiceClient interface.
type MockWalletServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockWalletServiceClientMockRecorder
	isgomock struct{}
}

// MockWalletServiceClientMockRecorder is the mock recorder for MockWalletServiceClient.
type MockWalletServiceClientMockRecorder struct {
	mock *MockWalletServiceClient
}

// NewMockWalletServiceClient creates a new mock instance.
func NewMockWalletServiceClient(ctrl *gomock.Controller) *MockWalletServiceClient {
	mock := &MockWalletServiceClient{ctrl: ctrl}
	mock.recorder = &MockWalletServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletServiceClient) EXPECT() *MockWalletServiceClientMockRecorder {
	return m.recorder
}

// ReserveBalance mocks base method.
func (m *MockWalletServiceClient) ReserveBalance(ctx context.Context, in interface{}, opts ...grpc.CallOption) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReserveBalance", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveBalance indicates an expected call of ReserveBalance.
func (mr *MockWalletServiceClientMockRecorder) ReserveBalance(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveBalance", reflect.TypeOf((*MockWalletServiceClient)(nil).ReserveBalance), varargs...)
}

// CommitReservation mocks base method.
func (m *MockWalletServiceClient) CommitReservation(ctx context.Context, in interface{}, opts ...grpc.CallOption) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CommitReservation", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitReservation indicates an expected call of CommitReservation.
func (mr *MockWalletServiceClientMockRecorder) CommitReservation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitReservation", reflect.TypeOf((*MockWalletServiceClient)(nil).CommitReservation), varargs...)
}

// CancelReservation mocks base method.
func (m *MockWalletServiceClient) CancelReservation(ctx context.Context, in interface{}, opts ...grpc.CallOption) (interface{}, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CancelReservation", varargs...)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelReservation indicates an expected call of CancelReservation.
func (mr *MockWalletServiceClientMockRecorder) CancelReservation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelReservation", reflect.TypeOf((*MockWalletServiceClient)(nil).CancelReservation), varargs...)
}
