// Code generated by MockGen. DO NOT EDIT.
// Source: internal/activity/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/activity/interfaces.go -destination=internal/mocks/mock_activities.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	workflow "github.com/cypherlabdev/order-validator-service/internal/workflow"
	gomock "go.uber.org/mock/gomock"
)

// MockValidationActivityInterface is a mock of ValidationActivityInterface interface.
type MockValidationActivityInterface struct {
	ctrl     *gomock.Controller
	recorder *MockValidationActivityInterfaceMockRecorder
	isgomock struct{}
}

// MockValidationActivityInterfaceMockRecorder is the mock recorder for MockValidationActivityInterface.
type MockValidationActivityInterfaceMockRecorder struct {
	mock *MockValidationActivityInterface
}

// NewMockValidationActivityInterface creates a new mock instance.
func NewMockValidationActivityInterface(ctrl *gomock.Controller) *MockValidationActivityInterface {
	mock := &MockValidationActivityInterface{ctrl: ctrl}
	mock.recorder = &MockValidationActivityInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationActivityInterface) EXPECT() *MockValidationActivityInterfaceMockRecorder {
	return m.recorder
}

// ValidateOrder mocks base method.
func (m *MockValidationActivityInterface) ValidateOrder(ctx context.Context, input workflow.ValidateOrderInput) (*workflow.ValidationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateOrder", ctx, input)
	ret0, _ := ret[0].(*workflow.ValidationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateOrder indicates an expected call of ValidateOrder.
func (mr *MockValidationActivityInterfaceMockRecorder) ValidateOrder(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateOrder", reflect.TypeOf((*MockValidationActivityInterface)(nil).ValidateOrder), ctx, input)
}

// MockWalletActivityInterface is a mock of WalletActivityInterface interface.
type MockWalletActivityInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWalletActivityInterfaceMockRecorder
	isgomock struct{}
}

// MockWalletActivityInterfaceMockRecorder is the mock recorder for MockWalletActivityInterface.
type MockWalletActivityInterfaceMockRecorder struct {
	mock *MockWalletActivityInterface
}

// NewMockWalletActivityInterface creates a new mock instance.
func NewMockWalletActivityInterface(ctrl *gomock.Controller) *MockWalletActivityInterface {
	mock := &MockWalletActivityInterface{ctrl: ctrl}
	mock.recorder = &MockWalletActivityInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletActivityInterface) EXPECT() *MockWalletActivityInterfaceMockRecorder {
	return m.recorder
}

// CancelReservation mocks base method.
func (m *MockWalletActivityInterface) CancelReservation(ctx context.Context, input workflow.CancelReservationInput) (*workflow.CancelReservationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelReservation", ctx, input)
	ret0, _ := ret[0].(*workflow.CancelReservationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelReservation indicates an expected call of CancelReservation.
func (mr *MockWalletActivityInterfaceMockRecorder) CancelReservation(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelReservation", reflect.TypeOf((*MockWalletActivityInterface)(nil).CancelReservation), ctx, input)
}

// CommitReservation mocks base method.
func (m *MockWalletActivityInterface) CommitReservation(ctx context.Context, input workflow.CommitReservationInput) (*workflow.CommitReservationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitReservation", ctx, input)
	ret0, _ := ret[0].(*workflow.CommitReservationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitReservation indicates an expected call of CommitReservation.
func (mr *MockWalletActivityInterfaceMockRecorder) CommitReservation(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitReservation", reflect.TypeOf((*MockWalletActivityInterface)(nil).CommitReservation), ctx, input)
}

// ReserveFunds mocks base method.
func (m *MockWalletActivityInterface) ReserveFunds(ctx context.Context, input workflow.ReserveFundsInput) (*workflow.ReserveFundsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveFunds", ctx, input)
	ret0, _ := ret[0].(*workflow.ReserveFundsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveFunds indicates an expected call of ReserveFunds.
func (mr *MockWalletActivityInterfaceMockRecorder) ReserveFunds(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveFunds", reflect.TypeOf((*MockWalletActivityInterface)(nil).ReserveFunds), ctx, input)
}

// MockOrderBookActivityInterface is a mock of OrderBookActivityInterface interface.
type MockOrderBookActivityInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrderBookActivityInterfaceMockRecorder
	isgomock struct{}
}

// MockOrderBookActivityInterfaceMockRecorder is the mock recorder for MockOrderBookActivityInterface.
type MockOrderBookActivityInterfaceMockRecorder struct {
	mock *MockOrderBookActivityInterface
}

// NewMockOrderBookActivityInterface creates a new mock instance.
func NewMockOrderBookActivityInterface(ctrl *gomock.Controller) *MockOrderBookActivityInterface {
	mock := &MockOrderBookActivityInterface{ctrl: ctrl}
	mock.recorder = &MockOrderBookActivityInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderBookActivityInterface) EXPECT() *MockOrderBookActivityInterfaceMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockOrderBookActivityInterface) CancelOrder(ctx context.Context, input workflow.CancelOrderInput) (*workflow.CancelOrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, input)
	ret0, _ := ret[0].(*workflow.CancelOrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockOrderBookActivityInterfaceMockRecorder) CancelOrder(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockOrderBookActivityInterface)(nil).CancelOrder), ctx, input)
}

// PlaceOrderInBook mocks base method.
func (m *MockOrderBookActivityInterface) PlaceOrderInBook(ctx context.Context, input workflow.PlaceOrderInBookInput) (*workflow.PlaceOrderInBookResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceOrderInBook", ctx, input)
	ret0, _ := ret[0].(*workflow.PlaceOrderInBookResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceOrderInBook indicates an expected call of PlaceOrderInBook.
func (mr *MockOrderBookActivityInterfaceMockRecorder) PlaceOrderInBook(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceOrderInBook", reflect.TypeOf((*MockOrderBookActivityInterface)(nil).PlaceOrderInBook), ctx, input)
}
